services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
    - "5432:5432"
    volumes:
    - mtgai_db_data:/var/lib/postgresql/data
    - ./init-user.sq;:/docker-entrypoint-initdb.d/init-user.sql
volumes:
  mtgai_db_data: 

